const enc=new TextEncoder();
const json=(data,status=200,extra={})=>new Response(status===204?null:JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','x-frame-options':'DENY','referrer-policy':'strict-origin-when-cross-origin',...extra}});
const bytes=s=>enc.encode(s);
const b64url=b=>btoa(String.fromCharCode(...new Uint8Array(b))).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_');
const from64=s=>Uint8Array.from(atob(s.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-s.length%4)%4)),c=>c.charCodeAt(0));
async function sign(secret,text){const key=await crypto.subtle.importKey('raw',bytes(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64url(await crypto.subtle.sign('HMAC',key,bytes(text)));}
async function equal(a,b){if(a.length!==b.length)return false;let v=0;for(let i=0;i<a.length;i++)v|=a.charCodeAt(i)^b.charCodeAt(i);return v===0;}
async function token(env,now=Math.floor(Date.now()/1000)){const payload=b64url(bytes(JSON.stringify({admin:true,iat:now,exp:now+604800,nonce:crypto.randomUUID()})));return `${payload}.${await sign(env.SESSION_SECRET,payload)}`;}
function cookie(req){return (req.headers.get('cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('session='))?.slice(8)||'';}
async function authed(req,env){const t=cookie(req);if(!t.includes('.'))return false;const [p,s]=t.split('.');if(!await equal(s,await sign(env.SESSION_SECRET,p)))return false;try{const c=JSON.parse(new TextDecoder().decode(from64(p)));return c.admin===true&&Number(c.exp)>=Math.floor(Date.now()/1000);}catch{return false;}}
async function data(req){try{return await req.json();}catch{return null;}}
function validate(p){if(!p||typeof p!=='object')return null;const title=String(p.title||'').trim(),category=String(p.category||'').trim(),content=String(p.content||'').trim(),status=String(p.status||'draft'),cover=String(p.cover||'').trim();if(!title||!content||title.length>120||category.length>40||content.length>200000||!['draft','published'].includes(status)||cover.length>300||(cover&&!cover.startsWith('/assets/')))return null;return{title,category,content,status,cover};}
const select=async(env,admin)=>{const q=admin?'SELECT * FROM posts ORDER BY updated_at DESC,id DESC':"SELECT * FROM posts WHERE status='published' ORDER BY COALESCE(published_at,created_at) DESC,id DESC";return (await env.DB.prepare(q).all()).results||[];};
async function handleRequest(req,env){const u=new URL(req.url),path=u.pathname,method=req.method,ok=await authed(req,env);
 if(path==='/api/login'&&method==='POST'){const p=await data(req),valid=typeof p?.password==='string'&&await equal(p.password,env.ADMIN_PASSWORD);if(!valid)return json({authenticated:false,error:'密码错误'},401);return json({authenticated:true},200,{'set-cookie':`session=${await token(env)}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=604800`});}
 if(path==='/api/logout'&&method==='POST')return json({authenticated:false},200,{'set-cookie':'session=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0'});
 if(path==='/api/session'&&method==='GET')return json({authenticated:ok});
 if(path==='/api/posts'&&method==='GET')return json(await select(env,false));
 if(path==='/api/admin/posts'&&method==='GET')return ok?json(await select(env,true)):json({error:'需要管理员登录'},401);
 if(path==='/api/posts'&&method==='POST'){if(!ok)return json({error:'需要管理员登录'},401);const p=validate(await data(req));if(!p)return json({error:'标题、分类、正文或状态无效'},422);const now=new Date().toISOString();const r=await env.DB.prepare('INSERT INTO posts(title,category,content,status,created_at,updated_at,published_at,cover) VALUES(?,?,?,?,?,?,?,?)').bind(p.title,p.category,p.content,p.status,now,now,p.status==='published'?now:null,p.cover).run();const id=r.meta.last_row_id;await env.DB.prepare('UPDATE posts SET slug=? WHERE id=?').bind(`post-${id}`,id).run();return json(await env.DB.prepare('SELECT * FROM posts WHERE id=?').bind(id).first(),201);}
 const m=path.match(/^\/api\/posts\/(\d+)$/);if(m&&['PUT','DELETE'].includes(method)){if(!ok)return json({error:'需要管理员登录'},401);const id=Number(m[1]),old=await env.DB.prepare('SELECT * FROM posts WHERE id=?').bind(id).first();if(!old)return json({error:'文章不存在'},404);if(method==='DELETE'){await env.DB.prepare('DELETE FROM posts WHERE id=?').bind(id).run();return json(null,204);}const p=validate(await data(req));if(!p)return json({error:'标题、分类、正文或状态无效'},422);const now=new Date().toISOString(),published=old.published_at||(p.status==='published'?now:null);await env.DB.prepare('UPDATE posts SET title=?,category=?,content=?,status=?,updated_at=?,published_at=?,cover=? WHERE id=?').bind(p.title,p.category,p.content,p.status,now,published,p.cover,id).run();return json(await env.DB.prepare('SELECT * FROM posts WHERE id=?').bind(id).first());}
 if(path.startsWith('/api/'))return json({error:'接口不存在'},404);return env.ASSETS.fetch(req);
}
export { handleRequest };
